### ISSUE TITLE
Issue with the guide provided on https://grails.org/download.html

### ISSUE THREAD

**Issue by KishoreVignesh** [grails/grails-static-website#30]
I am starting out with grails. I followed the tutorials to install grails using sdkman as provided on https://grails.org/download.html.

but when checking after the installation the following error appears.

[kishorevignesh@localhost ~]$ grails
Usage: 
     create-app [NAME] --profile=web 
     create-plugin [NAME] --profile=web-plugin 

| Error Error occurred running Grails CLI: null (Use --stacktrace to see the full trace)

and when it do. 

[kishorevignesh@localhost ~]$ grails --stacktrace
Usage: 
     create-app [NAME] --profile=web 
     create-plugin [NAME] --profile=web-plugin 

| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException
    at org.grails.cli.profile.git.GitProfileRepository.getAllProfiles(GitProfileRepository.groovy:72)
    at org.grails.cli.profile.commands.ListProfilesCommand.handle(ListProfilesCommand.groovy:43)
    at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:233)
    at org.grails.cli.GrailsCli.getBaseUsage(GrailsCli.groovy:176)
    at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:222)
    at org.grails.cli.GrailsCli.main(GrailsCli.groovy:153)
| Error Error occurred running Grails CLI: null

**Comment by graemerocher** [comment]
This is probably because you are running behind a proxy and need to configure said proxy

**Comment by jeffbrown** [comment]
It isn't clear what was going wrong (could be the proxy that Graeme mentioned).  Given the age of the issue I am going to close this.
